DROP TABLE REF_HEDIS_VALUE_SETS CASCADE CONSTRAINTS;

CREATE TABLE REF_HEDIS_VALUE_SETS
(
  VALUE_SET_NAME       VARCHAR2(64 BYTE)        NOT NULL,
  VALUE_SET_OID        VARCHAR2(64 BYTE)        NOT NULL,
  VALUE_SET_VERSION    VARCHAR2(32 BYTE)        NOT NULL,
  CODE                 VARCHAR2(16 BYTE)        NOT NULL,
  DEFINITION           VARCHAR2(512 BYTE),
  CODE_SYSTEM          VARCHAR2(16 BYTE)        NOT NULL,
  CODE_SYSTEM_OID      VARCHAR2(64 BYTE)        NOT NULL,
  CODE_SYSTEM_VERSION  VARCHAR2(32 BYTE)        NOT NULL
)
COMPRESS BASIC;

GRANT SELECT ON REF_HEDIS_VALUE_SETS TO PUBLIC;


INSERT INTO REF_HEDIS_VALUE_SETS
SELECT * FROM KHAYKINO.REF_HEDIS_VALUE_SETS;
COMMIT;