exec dbm.drop_tables('CNF_DW_REFRESH');

CREATE TABLE cnf_dw_refresh
(
  etl_step_num      NUMBER(10) CONSTRAINT pk_cnf_dw_refresh PRIMARY KEY,
  operation         VARCHAR2(100 BYTE) NOT NULL,       
  target_table      VARCHAR2(30 BYTE) NOT NULL,
  target_partition  VARCHAR2(256 BYTE),
  data_source       VARCHAR2(512 BYTE) NOT NULL,
  uk_col_list       VARCHAR2(256 BYTE),
  where_clause      VARCHAR2(2000 BYTE),
  delete_condition  VARCHAR2(2000 BYTE),
  error_table       VARCHAR2(30 BYTE)
);

GRANT SELECT ON cnf_dw_refresh TO PUBLIC;

truncate table cnf_dw_refresh;

INSERT INTO cnf_dw_refresh VALUES(401, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_cbnd', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(402, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_gp1d', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(403, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_gp2d', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(404, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_nbnd', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(405, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_nbxd', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(406, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_qhnd', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(407, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_sbnd', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(408, 'MERGE /*+ parallel(16) index(t) */', 'VISIT', NULL, 'SELECT * FROM visit_smnd', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(501, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(t idx_event_cbn_cid) */ * FROM event_cbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(502, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(t idx_event_gp1_cid) */ * FROM event_gp1 t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(503, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(t idx_event_gp2_cid) */ * FROM event_gp2 t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(504, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(t idx_event_nbn_cid) */ * FROM event_nbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(505, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(t idx_event_nbx_cid) */ * FROM event_nbx t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(506, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(t idx_event_qhn_cid) */ * FROM event_qhn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(507, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(t idx_event_sbn_cid) */ * FROM event_sbn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');
INSERT INTO cnf_dw_refresh VALUES(508, 'MERGE /*+ parallel(16) index(t) */', 'EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''EVENT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(t idx_event_smn_cid) */ * FROM event_smn t WHERE cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, 'ERR_EVENT');

INSERT INTO cnf_dw_refresh VALUES(511, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_cbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(512, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(pe) */ pe.* FROM proc_event_gp1 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(513, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(pe) */ pe.* FROM proc_event_gp2 pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(514, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_nbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(515, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(pe) */ pe.* FROM proc_event_nbx pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(516, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_qhn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(517, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_sbn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(518, 'MERGE /*+ parallel(16) index(t) */', 'PROC_EVENT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(pe) */ pe.* FROM proc_event_smn pe JOIN event e ON e.network = pe.network AND e.visit_id = pe.visit_id AND e.event_id = pe.event_id WHERE pe.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(521, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(r) */ r.* FROM result_cbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(522, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(r) */ r.* FROM result_gp1 r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(523, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(r) */ r.* FROM result_gp2 r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(524, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(r) */ r.* FROM result_nbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(525, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(r) */ r.* FROM result_nbx r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(526, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(r) */ r.* FROM result_qhn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(527, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(r) */ r.* FROM result_sbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(528, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''RESULT'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(r) */ r.* FROM result_smn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(531, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''CBN'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_cbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(532, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''GP1'') SELECT /*+ index(r) */ r.* FROM proc_event_archivet_gp1 r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(533, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''GP2'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_gp2 r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(534, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''NBN'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_nbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(535, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''NBX'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_nbx r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(536, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''QHN'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_qhn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(537, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''SBN'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_sbn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(538, 'MERGE /*+ parallel(16) index(t) */', 'RESULT', NULL, 'WITH cid AS (SELECT /*+ materialize */ NVL(etl.max_cid, 0) max_val FROM dim_hc_networks nw LEFT JOIN log_incremental_data_load etl ON etl.table_name = ''PROC_EVENT_ARCHIVE'' AND etl.network = nw.network WHERE nw.network = ''SMN'') SELECT /*+ index(r) */ r.* FROM proc_event_archive_smn r JOIN event e ON e.network = r.network AND e.visit_id = r.visit_id AND e.event_id = r.event_id WHERE r.cid > (SELECT max_val FROM cid)', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(710, 'MERGE', 'REF_ORDER_TYPES', NULL, 'SELECT DISTINCT order_type_id, name FROM order_type', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(711, 'MERGE', 'REF_VISIT_TYPES', NULL, 'SELECT DISTINCT visit_type_id, name, abbreviation FROM visit_type', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(712, 'MERGE', 'REF_HC_SPECIALTIES', NULL, 'V_REF_HC_SPECIALTIES', NULL, NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(820, 'MERGE', 'REF_PROC_EVENT_ARCHIVE_TYPES', NULL, 'SELECT DISTINCT archive_type_id, name FROM proc_event_archive_type', NULL, 'WHERE archive_type_id <> 0', NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(850, 'MERGE', 'DIM_PAYERS', NULL, 'PT008.PAYER_MAPPING', 'NETWORK,PAYER_ID', NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(890, 'MERGE /*+ PARALLEL(16)*/', 'REF_DIAGNOSES', NULL, 'V_REF_DIAGNOSES', NULL, NULL, 'DELETE_FLAG=''Y''', NULL);
INSERT INTO cnf_dw_refresh VALUES(895, 'EQUALIZE /*+ PARALLEL(16)*/', 'MAP_DIAGNOSES_CODES', NULL, 'V_MAP_DIAGNOSES_CODES', NULL, NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(900, 'MERGE /*+ PARALLEL(16)*/', 'DIM_HC_DEPARTMENTS', NULL, 'V_DIM_HC_DEPARTMENTS', 'NETWORK,LOCATION_ID', NULL, NULL, NULL);
INSERT INTO cnf_dw_refresh VALUES(905, 'MERGE /*+ PARALLEL(16)*/', 'DIM_PROCEDURES', NULL, 'V_DIM_PROCEDURES', 'NETWORK,SRC_PROC_ID', NULL, NULL, NULL);

INSERT INTO cnf_dw_refresh VALUES(1001, 'INSERT /*+ PARALLEL(32)*/', 'V_DIM_PATIENTS_STG', NULL, 'V_DIM_PATIENTS', NULL, 'WHERE change IS NOT NULL', NULL, NULL);

COMMIT;
