EXEC dbm.drop_tables('DSRIP_REPORT_TR010');

CREATE TABLE dsrip_report_tr010
(
  report_dt                      DATE NOT NULL,
  begin_dt                       DATE,
  end_dt                         DATE,
  network                        CHAR(3 BYTE) NOT NULL,
  facility_name                  VARCHAR2(64 BYTE),
  patient_id                     NUMBER(12) NOT NULL,
  visit_id                       NUMBER(12) NOT NULL,
  patient_name                   VARCHAR2(100 BYTE),
  mrn                            VARCHAR2(512 BYTE),
  apt_suite                      VARCHAR2(1024 BYTE),
  street_address                 VARCHAR2(1024 BYTE),
  city                           VARCHAR2(50 BYTE),
  state                          VARCHAR2(50 BYTE),
  country                        VARCHAR2(50 BYTE),
  mailing_code                   VARCHAR2(50 BYTE),
  home_phone                     VARCHAR2(50 BYTE),
  cell_phone                     VARCHAR2(50 BYTE),
  birthdate                      DATE,
  age                            NUMBER,
  pcp_id                         NUMBER,
  pcp_name                       VARCHAR2(60 BYTE),
  last_pcp_visit_id              NUMBER(12),
  last_pcp_visit_dt              DATE,
  final_visit_type               VARCHAR2(50 BYTE),
  initial_visit_type             VARCHAR2(50 BYTE),
  admission_dt                   DATE NOT NULL,
  discharge_dt                   DATE,
  payer_name                     VARCHAR2(150 BYTE),
  payer_group                    VARCHAR2(2048 BYTE),
  plan_name                      VARCHAR2(100 BYTE),
  medicaid_ind                   CHAR(1 CHAR),
  icd_code                       VARCHAR2(100 BYTE) NOT NULL,
  problem_description            VARCHAR2(1024 BYTE),
  asthma_cntrlr_med_name         VARCHAR2(175 BYTE),
  asthma_cntrlr_med_disp_date    DATE NOT NULL,
  asthma_other_med_disp_date     DATE NOT NULL,
  asthma_other_med_name          VARCHAR2(175 BYTE),
  asthma_cntrlr_med_cnt          NUMBER,
  asthma_other_med_cnt           NUMBER,
  med_luk_antbdy_dspns_evnt_cnt  NUMBER,
  cnt_of_total_medications       NUMBER,
  ratio                          NUMBER,
  numerator_flag                 CHAR(1 CHAR),
  clinic_visit_count             NUMBER,
  emergency_visit_count          NUMBER,
  inpatient_visit_count          NUMBER,
  outpatient_visit_count         NUMBER,
  CONSTRAINT pk_dsrip_report_tr010 PRIMARY KEY(report_dt, network, patient_id) USING INDEX COMPRESS
)
COMPRESS BASIC;

GRANT SELECT ON dsrip_report_tr010 TO PUBLIC;