CREATE TABLE DSRIP_REPORT_TR007_PDI90
(
  report_date            DATE,
  report_begin_date      DATE,
  report_end_date        DATE,
  pdi_14_flag            NUMBER,
  pdi_15_flag            NUMBER,
  pdi_16_flag            NUMBER,
  pdi_18_flag            NUMBER,
  age_group              VARCHAR2(14 CHAR),
  network                CHAR(3 BYTE)           NOT NULL,
  facility_name          VARCHAR2(64 BYTE),
  patient_name           VARCHAR2(100 BYTE),
  apt_suite              VARCHAR2(1024 BYTE),
  street_address         VARCHAR2(1024 BYTE),
  city                   VARCHAR2(50 BYTE),
  state                  VARCHAR2(50 BYTE),
  country                VARCHAR2(50 BYTE),
  zip_code               VARCHAR2(50 BYTE),
  home_phone             VARCHAR2(50 BYTE),
  cell_phone             VARCHAR2(50 BYTE),
  visit_id               NUMBER(12)             NOT NULL,
  mrn                    VARCHAR2(50 CHAR),
  patient_dob            DATE,
  visit_number           VARCHAR2(50 BYTE),
  patient_id             NUMBER(12)             NOT NULL,
  admission_date         DATE                   NOT NULL,
  discharge_time         DATE,
  financial_class        VARCHAR2(100 BYTE),
  payer_name             VARCHAR2(150 BYTE),
  payer_group            VARCHAR2(2048 BYTE),
  prim_care_provider     VARCHAR2(60 BYTE),
  attending_provider     VARCHAR2(60 BYTE),
  resident_provider      VARCHAR2(60 BYTE),
  age                    VARCHAR2(47 CHAR),
  pdi_14_inclusions      VARCHAR2(4000 BYTE),
  pdi_15_inclusions      VARCHAR2(4000 BYTE),
  pdi_16_inclusions      VARCHAR2(4000 BYTE),
  pdi_18_inclusions      VARCHAR2(4000 BYTE),
  pcp_visit_id           NUMBER(12),
  pcp_visit_dt           DATE,
  pcp_vst_facility_name  VARCHAR2(64 BYTE),
  payer_type             VARCHAR2(2048 BYTE)
)