CREATE MATERIALIZED VIEW mv_dsrip_tr002_023_a1c_cd_epic AS
 SELECT
  'QCPR' AS source,
  NULL AS empi,
  network,
  a1c_less_8,
  a1c_more_8,
  a1c_more_9,
  a1c_more_9_null,
  admission_dt_key,
  facility_key,
  facility_code,
  facility_name,
  patient_id,
  pat_lname,
  pat_fname,
  mrn,
  birthdate,
  age,
  apt_suite,
  street_address,
  city,
  state,
  country,
  mailing_code,
  home_phone,
  day_phone,
  pcp,
  visit_id,
  visit_type_id,
  visit_type,
  admission_dt,
  discharge_dt,
  medicaid_ind,
  payer_group,
  payer_key,
  payer_name,
  plan_id,
  plan_name,
  NULL AS inspayor1,
  NULL AS inspayor2,
  NULL AS inspayor3,
  NULL result_time_latest,
  onset_date,
  icd_code,
  problem_comments,
  a1c_final_calc_value,
  dsrip_report,
  --'N' AS epic_flag,

  report_dt,
  load_dt
 FROM
  dsrip_tr002_023_a1c_cdw
 UNION ALL
 SELECT
  source,
  empi,
  NULL,
  TO_NUMBER(a1c_less_then_8),
  TO_NUMBER(a1c_grt_eg_8),
  TO_NUMBER(a1c_grt_eg_9),
  TO_NUMBER(a1c_grt_eg_9_or_null),
  TO_NUMBER(TO_CHAR(encounter_date_latest, 'YYYYMMDD')),
  NULL,
  NULL,
  facility_latest,
  NULL,
  pat_last_name,
  pat_first_name,
  facility_mrn,
  birth_date,
  age_years,
  add_line_1,
  add_line_2,
  city,
  state,
  NULL,
  zip,
  pat_home_phone,
  pat_work_phone,
  pcp_general,
  NULL,
  NULL,
  NULL,
  encounter_date_latest,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  inspayor1,
  inspayor2,
  inspayor3,
  result_time_latest,
  NULL,
  NULL,
  NULL,
  result_value_latest,
  'DSRIP_TR002_023' AS dsrip_report,
  report_month_dt,
  etl_load_date
 FROM
  dsrip_tr002_023_a1c_epic