CREATE VIEW v_dsrip_report_tr018_qmed
AS
SELECT 
  NETWORK
  ,FACILITY_NAME
  ,PATIENT_ID
  ,PATIENT_NAME
  ,MRN
  ,BIRTHDATE
  ,APT_SUITE
  ,STREET_ADDRESS
  ,CITY
  ,STATE
  ,COUNTRY
  ,MAILING_CODE
  ,HOME_PHONE
  ,AGE
  ,VISIT_TYPE_NAME
  ,VISIT_ID
  ,CLINIC_CODE
  ,CLINIC_CODE_SERVICE
  ,CLINIC_CODE_DESC
  ,ADMISSION_DATE_TIME
  ,DISCHARGE_DATE_TIME
  ,PAYER_GROUP
  ,PAYER_NAME
  ,AGE_18_59
  ,AGE_60_85
  ,DIABETIC
  ,DIABETES_DX_CODE
  ,HYPERTENSION_DX_CODE
  ,HYPERTENSION_ONSET_DATE
  ,BP_READING_TIME
  ,SYSTOLIC_BP
  ,DIASTOLIC_BP
  ,NUMERATOR_FLAG1 as "HTN_Pts_age18-59_BP<140/90"
  ,NUMERATOR_FLAG2 as "HTN_DM_Pts_age60-85_BP<140/90"
  ,NUMERATOR_FLAG3 as "HTN_Pts_age60-85_BP<150/90"
FROM dsrip_report_tr018_qmed;
