--DROP TABLE tr010_asthma_med_ratio_report;

CREATE TABLE dsrip_tr13_asthma_med_mgt_rpt
(
  report_run_dt                  DATE,
  begin_dt                       DATE,
  end_dt                         DATE,
  network                        VARCHAR2(3 BYTE),
  facility_name                  VARCHAR2(100 BYTE),
  patient_id                     NUMBER(12),
  visit_id                       NUMBER(12),
  patient_name                   VARCHAR2(100 BYTE),
  mrn                            VARCHAR2(512 BYTE),
  apt_suite                      VARCHAR2(1024 BYTE),
  street_address                 VARCHAR2(1024 BYTE),
  city                           VARCHAR2(50 BYTE),
  state                          VARCHAR2(50 BYTE),
  country                        VARCHAR2(50 BYTE),
  mailing_code                   VARCHAR2(50 BYTE),
  home_phone                     VARCHAR2(50 BYTE),
  birthdate                      DATE,
  age                            NUMBER,
  emp_provider_id                NUMBER(12),
  emp_provider_name              VARCHAR2(60 BYTE),
  last_pcp_visit_id              NUMBER(12),
  last_pcp_visit_dt              DATE,
  latest_visit_type              VARCHAR2(50 BYTE),
  initial_visit_type             VARCHAR2(50 BYTE),
  admission_date_time            DATE,
  discharge_date_time            DATE,
  payer_name                     VARCHAR2(150 BYTE),
  payer_group                    VARCHAR2(2048 CHAR),
  plan_name                      VARCHAR2(1024 BYTE),
  medicaid_ind                   VARCHAR2(10 CHAR),
  icd_code                       VARCHAR2(100 BYTE),
  problem_description            VARCHAR2(1024 BYTE),
  asthma_cntrlr_med_name         VARCHAR2(175 BYTE),
  asthma_cntrlr_med_disp_date    DATE,
  asthma_other_med_disp_date     DATE,
  asthma_other_med_name          VARCHAR2(175 BYTE),
  asthma_cntrlr_med_cnt          NUMBER,
  asthma_other_med_cnt           NUMBER,
  med_luk_antbdy_dspns_evnt_cnt  NUMBER,
  cnt_of_total_medications       NUMBER,
  ratio                          NUMBER,
  numerator_flag                 CHAR(1 CHAR),
  clinic_visit_count             NUMBER,
  emergency_visit_count          NUMBER,
  inpatient_visit_count          NUMBER,
  outpatient_visit_count         NUMBER,
  CONSTRAINT pk_med_ratio_rpt PRIMARY KEY (network,patient_id,visit_id)
);