SET DEFINE OFF;
--SQL Statement which produced this data:
--
--  select * from META_CHANGES;
--
Insert into META_CHANGES
   (COMMENTS)
 Values
   ('Insert Asthma medications(40 - LEUKOTRIENE MODIFIERS, 41 - ANTIBODY INHIBITOR, 42 - ASTHMA CONTROLLER MEDICATION and 43 - OTHER ASTHMA MEDICATION) for TR010 report');


Insert into META_CRITERIA
   (CRITERION_ID, CRITERION_CD, DESCRIPTION)
 Values
   (40, 'MEDICATIONS:ASTHMA(LEUKOTRIENE MODIFIERS)', 'LEUKOTRIENE MODIFIERS');

Insert into META_CRITERIA
   (CRITERION_ID, CRITERION_CD, DESCRIPTION)
 Values
   (41, 'MEDICATIONS:ASTHMA(ANTIBODY INHIBITOR) ', 'ANTIBODY INHIBITOR');

Insert into META_CRITERIA
   (CRITERION_ID, CRITERION_CD, DESCRIPTION)
 Values
   (42, 'MEDICATIONS:ASTHMA(CONTROLLER MEDICATION)', 'ASTHMA CONTROLLER MEDICATION');

Insert into META_CRITERIA
   (CRITERION_ID, CRITERION_CD, DESCRIPTION)
 Values
   (43, 'MEDICATIONS:ASTHMA(OTHER ASTHMA MEDICATION)', 'OTHER ASTHMA MEDICATION');

Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (40, 'ALL', 'NONE', '%montelukast%', 'LEUKOTRIENE MODIFIERS', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (40, 'ALL', 'NONE', '%zafirlukast%', 'LEUKOTRIENE MODIFIERS', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (40, 'ALL', 'NONE', '%zileuton%', 'LEUKOTRIENE MODIFIERS', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (41, 'ALL', 'NONE', '%Xolair%', 'ANTIBODY INHIBITOR', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (41, 'ALL', 'NONE', '%omalizumab%', 'ANTIBODY INHIBITOR', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Accolate%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Advair Diskus%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Advair HFA%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Aerospan%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%AirDuo RespiClick%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Alvesco HFA%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%ArmonAir RespiClick%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Arnuity Ellipta%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Asmanex HFA%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Asmanex Twisthaler%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Breo Ellipta%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Cinqair%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Cromolyn Sodium%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Difil G%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Difil-G Forte%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Dulera%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Ed-Bron G%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Elixophyllin%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Flovent Diskus%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Flovent HFA%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Jay-Phyl%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Lufyllin%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Lufyllin-400%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Montelukast Sodium%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Nucala%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Pulmicort Flexhaler%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Pulmicort Respules%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Qvar with Dose Counter%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Qvar%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Singulair%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Symbicort%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Theo-24%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Theophylline ER%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Theophylline SR%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Xolair%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Zyflo CR%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%Zyflo%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%beclomethasone %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%budesonide %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%budesonide-formoterol%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%ciclesonide CFC free %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%cromolyn %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%dyphylline%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%dyphylline-guaifenesin %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%flunisolide %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%fluticasone %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%fluticasone CFC free %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%fluticasone furoate %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%fluticasone-salmeterol%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%formoterol-mometasone %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%guaifenesin-theophylline%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%mometasone %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%montelukast %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%omalizumab %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%theophylline %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%zafirlukast%', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (42, 'ALL', 'NONE', '%zileuton %', 'ASTHMA CONTROLLER MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%A-Hydrocort%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%A-Methapred%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Albuterol Extended Release%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Albuterol Sulfate%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Albuterol-Ipratropium Bromide%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Anoro Ellipta%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Arcapta Neohaler%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Atrovent HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Baycadron%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Bevespi Aerosphere%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Brovana%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Combivent Respimat%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Cortef%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Cortisone Acetate%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Deltasone%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%DexPak%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Dexamethasone Intensol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Dexamethasone Sodium Phosphate%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%DuoNeb%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Flo-Pred%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Foradil Aerolizer%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Incruse Ellipta%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Ipratropium Bromide%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Levalbuterol Tartrate HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%LoCort%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Maxair Autohaler%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Medrol Dosepak%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Medrol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Metaproterenol Sulfate%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Millipred DP%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Millipred%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Orapred ODT%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Orapred%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Pediapred%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Perforomist%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Prelone%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%ProAir HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%ProAir RespiClick%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Proventil HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Rayos%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%SOLU-Medrol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Serevent Diskus%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Solu-CORTEF%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Spiriva Respimat%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Spiriva%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Stiolto Respimat%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Striverdi Respimat%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Tudorza Pressair%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Utibron Neohaler%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Ventolin HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Veripred 20%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%VoSpire ER%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Xopenex Concentrate%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Xopenex HFA%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Xopenex%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%Zema Pak%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%aclidinium bromide %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%albuterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%cortisone %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%dexamethasone %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%fluticasone-vilanterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%glycopyrrolate-indacaterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%hydrocortisone %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%indacaterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%ipratropium CFC free %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%ipratropium%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%levalbuterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%metaproterenol %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%methylprednisolone %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%olodaterol %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%olodaterol-tiotropium %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%pirbuterol%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%prednisolone%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%prednisone%', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%salmeterol %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%tiotropium %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%umeclidinium %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
Insert into META_CONDITIONS
   (CRITERION_ID, NETWORK, QUALIFIER, VALUE, VALUE_DESCRIPTION, 
    CONDITION_TYPE_CD, COMPARISON_OPERATOR, INCLUDE_EXCLUDE_IND)
 Values
   (43, 'ALL', 'NONE', '%umeclidinium-vilanterol %', 'OTHER ASTHMA MEDICATION', 
    'MED', 'LIKE', 'I');
COMMIT;
